package(default_visibility = ["//visibility:public"])

cc_binary(
    name="hello_world",
    srcs=["hello_world.cpp"]
)

cc_binary(
    name="data_types",
    defines=["BAZEL_PLATFORM"],
    srcs=["data_types.cpp"]
)
